package cmd

import (
	"github.com/spf13/cobra"
)

// logCmd represents the log command
var logCmd = &cobra.Command{
	Use:   "log",
	Short: "Displays the logs of the cloudwatch group",
	Long:  `Real-time view of the stream of logs generated by the application, available on the cloudwatch.`,
	Run: func(cmd *cobra.Command, args []string) {
	},
}

func init() {
	rootCmd.AddCommand(logCmd)

}
